<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'testlink');
define('DB_HOST', 'db');
define('DB_NAME', 'testlink_db');
define('DB_TABLE_PREFIX', '');
?>