version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:v1
    container_name: backend
    restart: unless-stopped
    links:
      - db
    ports:
      - 9000:9000
    environment:
      TESTLINK_USERNAME: '${TESTLINK_USERNAME}'
      TESTLINK_PASSWORD: '${TESTLINK_PASSWORD}'
      TESTLINK_EMAIL: '${TESTLINK_EMAIL}'
    volumes:
      - ./apps/testlink:/var/www/html/testlink:rw
    networks:
      - testlink-network
  web:
    image: nginx:latest
    restart: unless-stopped
    container_name: web
    links:
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./apps/testlink:/var/www/html/testlink:rw
    networks:
      - testlink-network      
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db
    command: --init-file ./apps/testlink/install/sql/mysql/testlink_create_tables.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - ./apps/db:/var/lib/mysql
    networks:
      - testlink-network
networks:
  testlink-network:
    driver: bridge
