version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:v1
    container_name: backend
    restart: unless-stopped
    links:
      - db
    environment:
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'
      DB_NAME: '${DB_NAME}'
      DB_HOST: '${DB_HOST}'
    volumes:
      - testlink:/var/www/html/testlink:rw
    networks:
      - testlink-network
  web:
    image: nginx:latest
    restart: unless-stopped
    container_name: web
    links:
      - backend
    ports:
      - 8086:80
    volumes:
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
      - ./apps/nginx:/var/log/nginx:rw
      - testlink:/var/www/html/testlink:rw
    networks:
      - testlink-network      
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - ./apps/db:/var/lib/mysql
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - testlink-network
networks:
  testlink-network:
    driver: bridge
volumes:
  testlink: {}