version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:v1
    container_name: backend
    restart: unless-stopped
    links:
      - db
    environment:
      TESTLINK_USERNAME: '${TESTLINK_USERNAME}'
      TESTLINK_PASSWORD: '${TESTLINK_PASSWORD}'
      TESTLINK_EMAIL: '${TESTLINK_EMAIL}'
    volumes:
      - testlink:/var/www/html/testlink:rw
    networks:
      - testlink-network
  web:
    image: nginx:latest
    restart: unless-stopped
    container_name: web
    links:
      - backend
    ports:
      - 8086:80
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./apps/nginx/log:/var/log/nginx:rw
      - testlink:/var/www/html/testlink:rw
    networks:
      - testlink-network      
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db
#    command: --init-file /tmp/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - ./apps/db:/var/lib/mysql
      - ./init.sql:/tmp/init.sql
    networks:
      - testlink-network
networks:
  testlink-network:
    driver: bridge
volumes:
  testlink: {}